// This file is auto-generated by @hey-api/openapi-ts
export const WorkerStatusSchema = {
    type: 'string',
    enum: ['idle', 'working', 'paused'],
    description: 'Current status of a worker'
};
export const TaskStatusSchema = {
    type: 'string',
    enum: ['ready', 'leased', 'in_progress', 'blocked', 'pr_opened', 'merged'],
    description: 'Current status of a task'
};
export const TrustTierSchema = {
    type: 'string',
    enum: ['untrusted', 'basic', 'trusted', 'maintainer'],
    description: 'Trust level for worker access control'
};
export const RegisterWorkerRequestSchema = {
    type: 'object',
    required: ['name', 'skills', 'capacity_points', 'max_concurrent_tasks'],
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            maxLength: 120,
            description: 'Human-readable worker name'
        },
        github_handle: {
            type: 'string',
            maxLength: 120,
            nullable: true,
            description: 'GitHub username for attribution'
        },
        skills: {
            type: 'array',
            items: {
                type: 'string'
            },
            description: 'List of skills/technologies the worker can handle'
        },
        capacity_points: {
            type: 'integer',
            minimum: 1,
            maximum: 100,
            default: 5,
            description: 'Daily capacity in points'
        },
        max_concurrent_tasks: {
            type: 'integer',
            minimum: 1,
            maximum: 20,
            default: 2,
            description: 'Maximum number of concurrent task assignments'
        }
    }
};
export const RegisterWorkerResponseSchema = {
    type: 'object',
    required: ['worker_id', 'token'],
    properties: {
        worker_id: {
            type: 'string',
            description: 'Unique worker identifier'
        },
        token: {
            type: 'string',
            description: 'Bearer token for authentication'
        }
    }
};
export const HeartbeatRequestSchema = {
    type: 'object',
    properties: {
        status: {
            '$ref': '#/components/schemas/WorkerStatus',
            default: 'idle'
        },
        note: {
            type: 'string',
            maxLength: 500,
            nullable: true,
            description: 'Optional status message'
        }
    }
};
export const HeartbeatResponseSchema = {
    type: 'object',
    required: ['ok', 'server_time'],
    properties: {
        ok: {
            type: 'boolean',
            default: true
        },
        server_time: {
            type: 'string',
            format: 'date-time',
            description: 'Current server timestamp'
        }
    }
};
export const TaskArtifactSchema = {
    type: 'object',
    properties: {
        pr_url: {
            type: 'string',
            format: 'uri',
            nullable: true,
            description: 'GitHub PR URL'
        },
        commit_sha: {
            type: 'string',
            nullable: true,
            description: 'Git commit SHA'
        },
        patch_url: {
            type: 'string',
            format: 'uri',
            nullable: true,
            description: 'URL to patch file'
        },
        extra: {
            type: 'object',
            nullable: true,
            additionalProperties: true,
            description: 'Additional artifact metadata'
        }
    }
};
export const LeaseViewSchema = {
    type: 'object',
    required: ['task_id', 'repo', 'title', 'estimate_points', 'priority', 'required_skills', 'lease_expires_at'],
    properties: {
        task_id: {
            type: 'string',
            description: 'Unique task identifier'
        },
        repo: {
            type: 'string',
            description: 'Repository identifier'
        },
        title: {
            type: 'string',
            description: 'Task title'
        },
        description: {
            type: 'string',
            nullable: true,
            description: 'Detailed task description'
        },
        estimate_points: {
            type: 'integer',
            minimum: 1,
            maximum: 100,
            description: 'Estimated effort in points'
        },
        priority: {
            type: 'integer',
            minimum: 0,
            maximum: 1000,
            description: 'Task priority (higher = more important)'
        },
        area: {
            type: 'string',
            maxLength: 120,
            nullable: true,
            description: 'Code area for conflict avoidance'
        },
        tier: {
            type: 'integer',
            minimum: 0,
            maximum: 3,
            default: 0,
            description: 'Risk tier (0=safe, 3=high-risk)'
        },
        required_skills: {
            type: 'array',
            items: {
                type: 'string'
            },
            description: 'Required skills for this task'
        },
        lease_expires_at: {
            type: 'string',
            format: 'date-time',
            description: 'When the lease expires'
        }
    }
};
export const WorkResponseSchema = {
    type: 'object',
    required: ['worker_id', 'leases'],
    properties: {
        worker_id: {
            type: 'string',
            description: 'Worker identifier'
        },
        leases: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/LeaseView'
            },
            description: 'Assigned task leases'
        }
    }
};
export const TaskStatusUpdateRequestSchema = {
    type: 'object',
    required: ['status'],
    properties: {
        status: {
            type: 'string',
            enum: ['in_progress', 'blocked', 'pr_opened', 'merged'],
            description: 'New task status'
        },
        message: {
            type: 'string',
            maxLength: 4000,
            nullable: true,
            description: 'Optional status message'
        },
        artifact: {
            '$ref': '#/components/schemas/TaskArtifact'
        }
    }
};
export const RepoCreateRequestSchema = {
    type: 'object',
    required: ['repo'],
    properties: {
        repo: {
            type: 'string',
            minLength: 1,
            maxLength: 200,
            description: "Repository key (e.g. 'demo' or 'owner/name')"
        },
        max_open_prs: {
            type: 'integer',
            minimum: 0,
            maximum: 100,
            default: 3,
            description: 'Maximum open PRs (0 disables assignments)'
        },
        area_locks_enabled: {
            type: 'boolean',
            default: true,
            description: 'Enable area-based conflict prevention'
        }
    }
};
export const RepoCreateResponseSchema = {
    type: 'object',
    required: ['ok', 'repo'],
    properties: {
        ok: {
            type: 'boolean',
            default: true
        },
        repo: {
            type: 'string',
            description: 'Created repository identifier'
        }
    }
};
export const TaskCreateRequestSchema = {
    type: 'object',
    required: ['repo', 'title'],
    properties: {
        repo: {
            type: 'string',
            minLength: 1,
            maxLength: 200,
            description: 'Repository identifier'
        },
        title: {
            type: 'string',
            minLength: 1,
            maxLength: 300,
            description: 'Task title'
        },
        description: {
            type: 'string',
            nullable: true,
            description: 'Detailed task description'
        },
        estimate_points: {
            type: 'integer',
            minimum: 1,
            maximum: 100,
            default: 1,
            description: 'Estimated effort in points'
        },
        priority: {
            type: 'integer',
            minimum: 0,
            maximum: 1000,
            default: 10,
            description: 'Task priority (higher = more important)'
        },
        required_skills: {
            type: 'array',
            items: {
                type: 'string'
            },
            description: 'Required skills for this task'
        },
        area: {
            type: 'string',
            maxLength: 120,
            nullable: true,
            description: 'Code area for conflict avoidance'
        },
        tier: {
            type: 'integer',
            minimum: 0,
            maximum: 3,
            default: 0,
            description: 'Risk tier (0=safe, 3=high-risk)'
        }
    }
};
export const TaskCreateResponseSchema = {
    type: 'object',
    required: ['ok', 'task_id'],
    properties: {
        ok: {
            type: 'boolean',
            default: true
        },
        task_id: {
            type: 'string',
            description: 'Created task identifier'
        }
    }
};
export const WorkerReputationSchema = {
    type: 'object',
    required: ['worker_id', 'reputation_score', 'trust_tier', 'metrics'],
    properties: {
        worker_id: {
            type: 'string',
            description: 'Worker identifier'
        },
        reputation_score: {
            type: 'number',
            minimum: 0,
            maximum: 100,
            description: 'Overall reputation score (0-100)'
        },
        trust_tier: {
            '$ref': '#/components/schemas/TrustTier'
        },
        metrics: {
            type: 'object',
            required: ['completion_rate', 'avg_pr_quality', 'on_time_delivery', 'total_tasks'],
            properties: {
                completion_rate: {
                    type: 'number',
                    minimum: 0,
                    maximum: 1,
                    description: 'Percentage of tasks completed successfully'
                },
                avg_pr_quality: {
                    type: 'number',
                    minimum: 0,
                    maximum: 5,
                    description: 'Average PR quality rating'
                },
                on_time_delivery: {
                    type: 'number',
                    minimum: 0,
                    maximum: 1,
                    description: 'Percentage of tasks completed on time'
                },
                total_tasks: {
                    type: 'integer',
                    minimum: 0,
                    description: 'Total number of tasks completed'
                }
            }
        }
    }
};
export const TrustTierUpdateRequestSchema = {
    type: 'object',
    required: ['tier'],
    properties: {
        tier: {
            '$ref': '#/components/schemas/TrustTier'
        },
        reason: {
            type: 'string',
            maxLength: 500,
            description: 'Reason for trust tier change'
        }
    }
};
export const AnalyticsMetricsSchema = {
    type: 'object',
    required: ['repo', 'period', 'metrics'],
    properties: {
        repo: {
            type: 'string',
            description: 'Repository identifier'
        },
        period: {
            type: 'string',
            description: 'Time period for metrics'
        },
        metrics: {
            type: 'object',
            required: ['tasks_completed', 'avg_completion_time', 'worker_utilization', 'pr_merge_rate'],
            properties: {
                tasks_completed: {
                    type: 'integer',
                    minimum: 0,
                    description: 'Number of tasks completed in period'
                },
                avg_completion_time: {
                    type: 'string',
                    description: 'Average time to complete tasks'
                },
                worker_utilization: {
                    type: 'number',
                    minimum: 0,
                    maximum: 1,
                    description: 'Worker capacity utilization rate'
                },
                pr_merge_rate: {
                    type: 'number',
                    minimum: 0,
                    maximum: 1,
                    description: 'Percentage of PRs that get merged'
                },
                bottlenecks: {
                    type: 'array',
                    items: {
                        type: 'string'
                    },
                    description: 'Identified system bottlenecks'
                }
            }
        }
    }
};
export const AuditEventSchema = {
    type: 'object',
    required: ['timestamp', 'event_type', 'actor', 'target'],
    properties: {
        timestamp: {
            type: 'string',
            format: 'date-time',
            description: 'When the event occurred'
        },
        event_type: {
            type: 'string',
            enum: ['task_assigned', 'task_completed', 'worker_registered', 'repo_created', 'trust_tier_changed'],
            description: 'Type of audit event'
        },
        actor: {
            type: 'string',
            description: 'Who performed the action (worker_id, admin, system)'
        },
        target: {
            type: 'string',
            description: 'What was affected (task_id, worker_id, repo)'
        },
        details: {
            type: 'object',
            additionalProperties: true,
            description: 'Additional event context'
        }
    }
};
export const GitHubSyncRequestSchema = {
    type: 'object',
    required: ['sync_type'],
    properties: {
        sync_type: {
            type: 'string',
            enum: ['read_only', 'bidirectional'],
            description: 'Type of GitHub synchronization'
        },
        write_permissions: {
            type: 'array',
            items: {
                type: 'string',
                enum: ['comments', 'labels', 'status']
            },
            description: 'Requested write permissions'
        }
    }
};
export const GitHubSyncResponseSchema = {
    type: 'object',
    required: ['webhook_url', 'permissions_granted'],
    properties: {
        webhook_url: {
            type: 'string',
            format: 'uri',
            description: 'Webhook URL for GitHub integration'
        },
        permissions_granted: {
            type: 'array',
            items: {
                type: 'string'
            },
            description: 'Granted GitHub permissions'
        }
    }
};
export const ErrorResponseSchema = {
    type: 'object',
    required: ['error', 'message'],
    properties: {
        error: {
            type: 'string',
            description: 'Error code identifier'
        },
        message: {
            type: 'string',
            description: 'Human-readable error message'
        },
        details: {
            type: 'object',
            description: 'Additional error context',
            additionalProperties: true
        }
    }
};
//# sourceMappingURL=schemas.gen.js.map